# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "KKSimpleAnalyticsExample" do
    pod 'KKSimpleAnalytics', :path => '/Users/konstantin/My_Projects/BLogAndOther/KKSimpleAnalytics/KKSimpleAnalytics.podspec'
end

target "KKSimpleAnalyticsExampleTests" do

end

