# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "KKSimpleAnalytics" do
    pod 'GoogleAnalytics-iOS-SDK', '3.0.6'
    pod 'JRSwizzle', '1.0'
end

target "KKSimpleAnalyticsTests" do

end

